In [28]:
 pip install sklearn

Note: you may need to restart the kernel to use updated packages.


In [29]:
pip install datasets

Note: you may need to restart the kernel to use updated packages.


In [30]:
from datasets import load_dataset

imdb_dataset = load_dataset("imdb")['train']
print(imdb_dataset[-1])

Found cached dataset imdb (C:/Users/thoma/.cache/huggingface/datasets/imdb/plain_text/1.0.0/2fdd8b9bcadd6e7055e742a706876ba43f19faee861df134affd7a3f60fc38a1)


  0%|          | 0/3 [00:00<?, ?it/s]

{'text': 'The story centers around Barry McKenzie who must go to England if he wishes to claim his inheritance. Being about the grossest Aussie shearer ever to set foot outside this great Nation of ours there is something of a culture clash and much fun and games ensue. The songs of Barry McKenzie(Barry Crocker) are highlights.', 'label': 1}


In [31]:
train_data = []
train_data_labels = []
for item in imdb_dataset:
  train_data.append(item['text'])
  train_data_labels.append(item['label'])
print(train_data[-1])
print(train_data_labels[-1])

The story centers around Barry McKenzie who must go to England if he wishes to claim his inheritance. Being about the grossest Aussie shearer ever to set foot outside this great Nation of ours there is something of a culture clash and much fun and games ensue. The songs of Barry McKenzie(Barry Crocker) are highlights.
1


In [32]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(analyzer='word',max_features=5000,lowercase=True)
features = vectorizer.fit_transform(train_data).toarray()

In [89]:
print(features.shape)
print(vectorizer.get_feature_names_out())
#print(vectorizer)
#print(features)

(25000, 5000)
['00' '000' '10' ... 'zombie' 'zombies' 'zone']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [33]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(features,train_data_labels,train_size=0.75,random_state=100)

In [34]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
model = MultinomialNB(alpha = 0.5, class_prior=[0.60,0.40])
model2 = DecisionTreeClassifier() # Part second model added

In [35]:
model = model.fit(X=X_train,y=y_train)
model2 = model2.fit(X=X_train,y=y_train)

In [36]:
y_pred = model.predict(X_val)
y_pred2 = model2.predict(X_val)

In [37]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_val,y_pred))
print(accuracy_score(y_val,y_pred2))# the same accuracy here(not same anymore)

0.8384
0.6944


In [38]:
#Part 4
test_data = ['The truly epic blockbuster we needed.', 'If theres any movie that deserves to be seen in the theaters with big screens and booming speakers. Its :Top Gun Maverick.One of my best experiences in years!','Best Sequel yet', "Not bad, but wayy overrated.", "Terrible plot and script, boring and pointless", "Didnt make much sense", "Very uninteresting", "What A Mess! I Want My 2 Hours Back!", "I could have actually cried watching this. Dr. Strange is one of my favourite Marvel movies but this was just plain awful. 1 hour in and I was debating leaving. Marvel are losing their touch, and ever since Endgame, it just hasn't felt the same, apart from NWH. Sam Raimi messed up big time.", "I'm unsure of why this has received a high IMDb rating. It's rubbish and slow and nonsensical. Instead this film rakes in all past cast members for some obscure reminiscent feelgood film. Trash at its Hollywood best. You've been warned.", "Don't watch the trailers. Just watch the movie. I'm not going to say much. It's amazing. And I'm in complete disbelief that it actually happened. Well-made, well-acted, well-directed. Fun, funny and crazy with a ton of heart. Can't wait to watch it again.", "Best Movie Of The Year", "They did it! A Spider-Man trilogy finally stuck the landing! Spider-Man: No Way Home is an impressive culmination of the films that came before it, with an engaging storyline, exciting action, laugh out loud moments, and dramatic consequences. The beginning climb is a little slow, but it's an exhilarating ride once things get swinging. I don't exactly know how this movie will hold up after multiple viewings, as there are some plot points that don't quite make sense when you start to think about them, but I thoroughly enjoyed myself this first time.", "I'm unsure of why this has received a high IMDb rating. It's rubbish and slow and nonsensical. Instead this film rakes in all past cast members for some obscure reminiscent feelgood film. Trash at its Hollywood best. You've been warned.", "This film is an emotional rollercoaster with some of the coolest superhero plot lines ever drawn up. It's straight up the most epic Marvel film that will probably ever be created. I don't see how Marvel could ever top this, but getting to see these characters all together at least one last time was a reward all on its own.", "Thee same movie over and over, that´s the MCU. The same repetitive jokes and villain, only with a different cape ... The story is boring and tries a lot to be something it is not!!!!", "Oh dear. I can't believe how diisapointed I am. So dissapointed. I wanted to cry.", "Detective Batman at its peak! Great storyline. Just as dark a universe as we've come to expect from DC. The gloomy, gritty, dark tone of this film is exactly what I wanted. When you think the movie is over, there's more. Beautiful cinematography. Great score.", "Everything I wanted and more", "Matt Reeves The Batman is a hell of a movie, it is the darkest live action Batman movie ever made, and the longest one too, The Batman fills with a top notch action sequence that not only exciting, but it's cinematic too, the cinematography was just incredible, Michael Giacchino The Batman theme song has just become one of my favorite movie theme song ever, it's enduringly great, the action is perfect itself without the theme but they making it even more perfect with the theme in the background especially when Batman shows up, it really making me hyped more because of that, Colin Farrell transformation is as amazing as his performance as The Penguin, Paul Dano performance is giving me a Heath Ledger Joker vibes but not trying to be Heath Ledger Joker which is still great, Paul Dano The Riddler is still a terrifying and a very disturbing villain, Zoe Kravits performances as Catwoman was amazing though she is not as wild as Michelle Pfeiffer in Batman Returns but boy did her gesture and look is as wild as Michelle Pfeiffer, and the Catwoman fighting sequence is definitely a win for Zoe and i did still like her a lot in here, and in the end we got The Batman himself, Robert Pattinson, all i can say about him as The Batman is that i hope everybody is starting to know him as the guy who play The Batman which is a really good movie and not the guy who play in the horrible Twilight film anymore because he is indeed an awesome Batman, now he was become my second favorite Batman next to Christian Bale in number one still, the story of The Batman itself is great, and my only problem with the movie is that there is quite a lot of particular scene that for me are just very slow or too slow, it's not boring but i feel like they can make it a little bit faster, if it's only one or two or three scene i probably still can forgive it but unfortunately it happens more than that, but at in the end The Batman is still a hell of a great movie, it's still amazing and it's still incredible, i was impress by most of the thing that happens, i was excited, i was hyped, i was stunt by all the amazing thing that they've done, The Batman is fire!!!."]
test_data_labels = [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1]

test_pred=model.predict(vectorizer.transform(test_data).toarray())
print(accuracy_score(test_pred,test_data_labels))
test_pred=model2.predict(vectorizer.transform(test_data).toarray())
print(accuracy_score(test_pred,test_data_labels))

0.75
0.65


In [14]:
#Part 3
#accuracy increased from 0.70368 to 0.8384.
#The maxium number of features in the countvectorizer command was increased to 5000 this was done as the more words
# that are analised the more inforation we have to work with making the model more accurate.
#Also I changed some of the parameters in the MultinomialNH function. I tred changing the value of the laplace and noticed when I decreased it to 0.5 that was the sweet spot for th most accuracy
#Also I tried adding prior probailities in the MultinomialNB function where I assumed the probability of a review being positive or negative was not equal. Changing this to 0.6 and 0.4 also increased the accuracy.

In [15]:
#Part 1 explaination 
#Used confusion_matrix() function with the y_val and y_pred which was used to calculate the accuracy to print out the confusion matrix
#I calculated the true postive rate by dividing all the correcly predicted postives by the true positives and false negatives
#I calculated the true negative rate by divide the true negatives by the true negatives plus false postives


In [39]:
#Assignment 2-Part 1
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_val,y_pred)
print(conf_mat)
#----------------------------------------------------------
TP = conf_mat[1, 1]
#print(TP)
TN = conf_mat[0, 0]
#print(TN)
FN = conf_mat[1, 0]
#print(FN)
FP = conf_mat[0, 1]
#print(FP)
TPR = TP/(TP+FN)
print(TPR)
TNR = TN/(TN+FP) 
print(TNR)


[[2726  408]
 [ 602 2514]]
0.806803594351733
0.8698149329929802


In [40]:
#Assignment 2-Part 2

test_data = ['The truly epic blockbuster we needed.', 'If theres any movie that deserves to be seen in the theaters with big screens and booming speakers. Its :Top Gun Maverick.One of my best experiences in years!','Best Sequel yet', "Not bad, but wayy overrated.", "Terrible plot and script, boring and pointless", "Didnt make much sense", "Very uninteresting", "What A Mess! I Want My 2 Hours Back!", "I could have actually cried watching this. Dr. Strange is one of my favourite Marvel movies but this was just plain awful. 1 hour in and I was debating leaving. Marvel are losing their touch, and ever since Endgame, it just hasn't felt the same, apart from NWH. Sam Raimi messed up big time.", "I'm unsure of why this has received a high IMDb rating. It's rubbish and slow and nonsensical. Instead this film rakes in all past cast members for some obscure reminiscent feelgood film. Trash at its Hollywood best. You've been warned.", "Don't watch the trailers. Just watch the movie. I'm not going to say much. It's amazing. And I'm in complete disbelief that it actually happened. Well-made, well-acted, well-directed. Fun, funny and crazy with a ton of heart. Can't wait to watch it again.", "Best Movie Of The Year", "They did it! A Spider-Man trilogy finally stuck the landing! Spider-Man: No Way Home is an impressive culmination of the films that came before it, with an engaging storyline, exciting action, laugh out loud moments, and dramatic consequences. The beginning climb is a little slow, but it's an exhilarating ride once things get swinging. I don't exactly know how this movie will hold up after multiple viewings, as there are some plot points that don't quite make sense when you start to think about them, but I thoroughly enjoyed myself this first time.", "I'm unsure of why this has received a high IMDb rating. It's rubbish and slow and nonsensical. Instead this film rakes in all past cast members for some obscure reminiscent feelgood film. Trash at its Hollywood best. You've been warned.", "This film is an emotional rollercoaster with some of the coolest superhero plot lines ever drawn up. It's straight up the most epic Marvel film that will probably ever be created. I don't see how Marvel could ever top this, but getting to see these characters all together at least one last time was a reward all on its own.", "Thee same movie over and over, that´s the MCU. The same repetitive jokes and villain, only with a different cape ... The story is boring and tries a lot to be something it is not!!!!", "Oh dear. I can't believe how diisapointed I am. So dissapointed. I wanted to cry.", "Detective Batman at its peak! Great storyline. Just as dark a universe as we've come to expect from DC. The gloomy, gritty, dark tone of this film is exactly what I wanted. When you think the movie is over, there's more. Beautiful cinematography. Great score.", "Everything I wanted and more", "Matt Reeves The Batman is a hell of a movie, it is the darkest live action Batman movie ever made, and the longest one too, The Batman fills with a top notch action sequence that not only exciting, but it's cinematic too, the cinematography was just incredible, Michael Giacchino The Batman theme song has just become one of my favorite movie theme song ever, it's enduringly great, the action is perfect itself without the theme but they making it even more perfect with the theme in the background especially when Batman shows up, it really making me hyped more because of that, Colin Farrell transformation is as amazing as his performance as The Penguin, Paul Dano performance is giving me a Heath Ledger Joker vibes but not trying to be Heath Ledger Joker which is still great, Paul Dano The Riddler is still a terrifying and a very disturbing villain, Zoe Kravits performances as Catwoman was amazing though she is not as wild as Michelle Pfeiffer in Batman Returns but boy did her gesture and look is as wild as Michelle Pfeiffer, and the Catwoman fighting sequence is definitely a win for Zoe and i did still like her a lot in here, and in the end we got The Batman himself, Robert Pattinson, all i can say about him as The Batman is that i hope everybody is starting to know him as the guy who play The Batman which is a really good movie and not the guy who play in the horrible Twilight film anymore because he is indeed an awesome Batman, now he was become my second favorite Batman next to Christian Bale in number one still, the story of The Batman itself is great, and my only problem with the movie is that there is quite a lot of particular scene that for me are just very slow or too slow, it's not boring but i feel like they can make it a little bit faster, if it's only one or two or three scene i probably still can forgive it but unfortunately it happens more than that, but at in the end The Batman is still a hell of a great movie, it's still amazing and it's still incredible, i was impress by most of the thing that happens, i was excited, i was hyped, i was stunt by all the amazing thing that they've done, The Batman is fire!!!."]
test_data_labels = [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1]

test_pred=model.predict(vectorizer.transform(test_data).toarray())
print(accuracy_score(test_pred,test_data_labels))#accuracy of model 1 0.75
test_pred2=model2.predict(vectorizer.transform(test_data).toarray())
print(accuracy_score(test_pred2,test_data_labels))#accuracy of model 2 decision tree 0.7

conf_mat = confusion_matrix(test_pred,test_data_labels)
print(conf_mat)
conf_mat2 = confusion_matrix(test_pred2,test_data_labels)
print(conf_mat2)#confusion matrix for model 2
a =(test_pred == 1) == (test_data_labels== 0)#15 correct = 0.75 # shows cases model classified correctly and incorrectly
b =(test_pred2 == 0) == (test_data_labels== 1)# 14 correct = 0.7 shows cases model classified correctly and incorrectly
print(a)
print(b)

#1) Where both outputs are true Cases that both models classified correctly [0, 2, 5, 6, 9, 10, 13, 14, 16, 18]
for y in [0, 2, 5, 6, 9, 10, 13, 14, 16, 18]:
    print(test_data[y])#prints out cases that both models classified correctly
    
#2) where both outputs are false, Cases that both models classified incorrectly [12]
print(test_data[12])#prints entry 12 in list which was classified incorrectly by both

#3) where output 1 is true and output 2 is false Cases that were correctly classified by model1 and incorrectly classified by model2
#[3, 4, 7, 8, 15]
for y in [3, 4, 7, 8, 15]:
    print(test_data[y])#prints these entries

#4) where output 1 is false and output 2 is true 4) Cases that were correctly classified by model2 and incorrectly classified by model1
#[1, 11, 17, 19]
for y in [1, 11, 17, 19]:
    print(test_data[y])#prints these entries
    
#model 2 was a lot more accurate at correctly classifying the positive reviews 
#while model 1 was much better at correctly classifying all the negative reviews
#model 1 assigned most reviews to negative
#model 2 assigned most reviews to positive
#Similar accuracy but looking at confusin matrix the models work very differently from each other

0.75
0.65
[[10  5]
 [ 0  5]]
[[4 1]
 [6 9]]
[ True False  True  True  True  True  True  True  True  True  True False
 False  True  True  True  True False  True False]
[ True  True  True False False  True  True False False  True  True  True
 False  True  True  True  True  True  True  True]
The truly epic blockbuster we needed.
Best Sequel yet
Didnt make much sense
Very uninteresting
I'm unsure of why this has received a high IMDb rating. It's rubbish and slow and nonsensical. Instead this film rakes in all past cast members for some obscure reminiscent feelgood film. Trash at its Hollywood best. You've been warned.
Don't watch the trailers. Just watch the movie. I'm not going to say much. It's amazing. And I'm in complete disbelief that it actually happened. Well-made, well-acted, well-directed. Fun, funny and crazy with a ton of heart. Can't wait to watch it again.
I'm unsure of why this has received a high IMDb rating. It's rubbish and slow and nonsensical. Instead this film rakes in 

In [44]:
#Assignment 2 Part 3
import numpy as np
importances = model2.feature_importances_

print(importances)# importance value of each feature
a = []
for k in importances:
    a.append(k)#prints
b = sorted(a)
#print(b)# sort list need number 50 from the top
x = b[len(b) - 50]
print(x)# x is the value of the 51th most important feature in this model

#for i,v in enumerate(importances):
  #  if(v > 0.0025183):
  #      print(i)# This gives value and index of the 50 most important features

ll = vectorizer.get_feature_names()#list of feature names
for i,v in enumerate(importances):#i is the index and v is the value of the feature
    if(v > 0.0025183):#this is the 51st most important values
        print(ll[i])#prints out the feature names
    
#I used my own method here to print out the 50 most important features of my decison tree classifier model.
#I used .feature_importances to get an array with the importance values of each feature.
#I then appended these values to a list 'a' and sorted this list
#I set the variable x equal to the importance value of the 51st most important feature
#I used .get_feaure_names() method to make a list of the feature names called 'll'
#I then used a for loop with the enumerate command to loop through the list of importance values
#Only selected those values greater than the 51st biggest value, so only the top 50 importance values
#I set i equal to the index of the importance value and v equal to the value itself
#I then printed out the feaure names that had an importance value greater than the 51st most important value
#This gives me a list of the 50 most important features of my model
#There is probably an easier way to do th

[0. 0. 0. ... 0. 0. 0.]
0.002490581467800634
amazing
and
awful
bad
beautiful
best
boring
both
br
could
crap
excellent
fails
good
great
him
in
is
it
just
lame
like
love
minutes
movie
no
not
nothing
of
on
pointless
poor
poorly
ridiculous
story
stupid
supposed
terrible
the
they
this
to
very
was
waste
with
wonderful
worst
would


In [45]:
#Assignemnt 2 Part 4 - A Difficult Test Set

test_data2 = ["It's hard to shake the uneasy feeling of this film. It's grim and foggy but at the core is the idea that when trauma is passed from person to person it will consume you. With that in hand, director Parker Finn plays on the idea that most people who suffer through awful events in life will have their past consume them if they don't confront them. Dr. Rose Cotter (Sosie Bacon) is a clinical psychologist who surrounds herself with the mentally broken people of New Jersey (add your own joke here). You can basically connect the dots as to how she became good at her job. One fateful day a girl comes into her office and gruesomely ends her own life. That launches Sosie's journey into her own madness. Slowly seeing things in her life. Or being haunted by voices of her past. Whatever it is knows her greatest pains. And exploits it. The mystery isn't completely satisfying to solve, but the constant moments of jerky jumpscares definitely make you feel on edge.What I particularly like is the uneasy camera work. It isn't afraid to linger long within the frame. Nor add dutch angles. It plays like 70's cinema. The frames make you squirm. Though much of the scares are telegraphed. This isn't a slasher gory flick. It's really a psychological mind bender. As mentioned before, the resolution won't make you happy. But then, it really is watching someone work through their own mental illness. If that is interesting to you, this is the movie for you.", "Given its premise that appears purely silly and gimmicky on the surface, I was shocked that I actually got psychologically wrapped up in the allegorical themes and characterization of Smile.","My assumptions for this film was that it would be repetitive with a bunch of cheap jump scares, and a story that would be a whirlwind of boredom. Almost similar to Truth or Dare.While this film was filled with a bunch of jump scares. They were executed in such a way that my anxiety was shooting through the roof. While Barbarian was able to spook me a bit. This film has my heart still racing an hour after the film has ended which is very uncommon for me.", "A horrifying look into trauma", "Going into this movie based on the trailer I kinda knew what I was getting myself into...but it was so much more than that! The storyline was very well drawn out...the jump scares were terrific. There may have been one too many...but hey...what's a gory horror movie without unexpected, uneccesary jump scares", "I wasn't scared during this film at all this is not a horror", "I literally laughed through-out this film not scary at all", "All the usual suspects are here again. Unsettling music scores with obvious build-up and climax, loud noises and brutal cutaways to keep you on edge, bait-and-switch scenes that play with what is real and what is not", "Can't take it seriously. Person next to me, slapped me in the face. Definitely more disturbed by people fucking around in the theatre.", "too busy laughing to take it seriously."]
test_data_labels2 = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
test_pred2=model.predict(vectorizer.transform(test_data2).toarray())
print(accuracy_score(test_pred2,test_data_labels2))
test_pred3=model2.predict(vectorizer.transform(test_data2).toarray())
print(accuracy_score(test_pred3,test_data_labels2))

conf_mat = confusion_matrix(test_pred2,test_data_labels2)
print(conf_mat)
conf_mat2 = confusion_matrix(test_pred3,test_data_labels2)
print(conf_mat2)#confusion matrix for model 2

#For the data in this test set I used user reviews from IMBD, metacritic and online forums on the new horror movie Smile.
#Since this is a horror film designed to be unnerving and sometimes hard to watch,
#I figured some of these postitve reviews would include words like uneasy, grim, foggy and hard to watch but meant in a positive way instead of the usual negative connotations these words have.
#I also included reviews that were positive about the movie giving people anxiety and being hard to watch which wouldn't usual be associated with positive emotions.
#But since this is a horror movie that is intended to make people anxious and be hard to watch at times this words are actually giving the movie props.
#For the negative reviews I used edgy/casual user reviews from metacritic which contained sarcasm and slang which is very difficult from the models to pick up on.
#I also picked reviews that commented on the movie being funny/laughable which in this context being a horror film review is a bad thing.
#Both models has exactly 50% accuracy which is not good as it is basically the same is just randomly guessing.
#Both models preform equally well but looking at the confusion matrixes actually classify very differently

0.5
0.5
[[4 4]
 [1 1]]
[[1 1]
 [4 4]]
